### ISSUE TITLE
Should not print "Jar uploaded...." even if the jar file is not successfully uploaded

### ISSUE THREAD

**Issue by aaronlin** [pishen/spark-deployer#3]

**Comment by pishen** [comment]
其實如果 upload 失敗，前一行的 sys.error 就會直接噴了，不過你會有這種反應代表你是 functional 的模範生XD

**Comment by pishen** [comment]
先在最後面用一個 if else 分開來 https://github.com/pishen/spark-deployer/commit/b58ab7ffc2a4c6c3d69650e3f1b27c9303eea38c
